title: TruteOrDare
description: >
  A blog that records my interest in Data Science.
permalink: ':title/'
url: 'www.truteordare.co.uk'

author: Jack Trute
author-img: 'profile.png'
about-author: I'm a Software Developer exploring Data Science.
social-twitter: '@truteordare'
social-github: 'truteordare'
social-email: 'contactme@truteordare.co.uk'

# discus-identifier: 
analytics: 'UA-179146840-1'

markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
